version: "3.3"
services:
  mariadb:
    image: mariadb:10.6
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_USER: pgl
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: pgl
      MYSQL_ROOT_PASSWORD: root

  # phpmyadmin:
  #   depends_on:
  #     - mariadb
  #   image: phpmyadmin/phpmyadmin
  #   ports:
  #     - "8081:80"
  #   environment:
  #     PMA_HOST: mariadb
  #     MYSQL_ROOT_PASSWORD: root

  backend:
    depends_on:
      - mariadb
    build: ./backend
    image: irigo-map-backend
    ports:
      - "8081:8080"
    environment:
      JWT_SECRET: Rr4lh67fkhbzczQirt11dFYbGHaEBFcSiNGYr4NMijvElDEjhyTcjw1Z1zeUwwaeMzr9uIgMEeCiJmNFEVPc0g==

  frontend:
    depends_on:
      - backend
    build: ./frontend
    image: irigo-map-frontend
    ports:
      - "8090:80"

volumes:
  db:
