package fr.eseo.equipe2.pglback.payload.request;

import com.sun.istack.NotNull;
import fr.eseo.equipe2.pglback.enumeration.Role;
import fr.eseo.equipe2.pglback.enumeration.UserSex;

import java.util.Date;

public class AddUserRequest {
    @NotNull
    private String firstName;
    @NotNull
    private String lastName;
    @NotNull
    private String email;
    @NotNull
    private UserSex sex;
    @NotNull
    private Date birthday;
    @NotNull
    private Role role;

    private Boolean autoGeneratedPassword;
    private String providedPassword;

    public String getFirstName() {
        return firstName;
    }

    public AddUserRequest setFirstName(String firstName) {
        this.firstName = firstName;
        return this;
    }

    public String getLastName() {
        return lastName;
    }

    public AddUserRequest setLastName(String lastName) {
        this.lastName = lastName;
        return this;
    }

    public String getEmail() {
        return email;
    }

    public AddUserRequest setEmail(String email) {
        this.email = email;
        return this;
    }

    public UserSex getSex() {
        return sex;
    }

    public AddUserRequest setSex(UserSex sex) {
        this.sex = sex;
        return this;
    }

    public Date getBirthday() {
        return birthday;
    }

    public AddUserRequest setBirthday(Date birthday) {
        this.birthday = birthday;
        return this;
    }

    public Role getRole() {
        return role;
    }

    public AddUserRequest setRole(Role role) {
        this.role = role;
        return this;
    }

    public Boolean getAutoGeneratedPassword() {
        return autoGeneratedPassword;
    }

    public AddUserRequest setAutoGeneratedPassword(Boolean autoGeneratedPassword) {
        this.autoGeneratedPassword = autoGeneratedPassword;
        return this;
    }

    public String getProvidedPassword() {
        return providedPassword;
    }

    public AddUserRequest setProvidedPassword(String providedPassword) {
        this.providedPassword = providedPassword;
        return this;
    }
}
