# JPA
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

# JWT
app.jwt.secret=GcqIStpE0Al8nv8FmC54fEYOcBy91rRBJymNNPPR1khv9xBZciWWsq0JKooSkklzk8LG7/XoXoC4RcUeJnhigmkbUsg07lLC4nqjvSHLDvdZs2USZdnhbin3x9g6e+aFDxwV58yIN0a38Fc3fV/WBybC+3HNCH3LWKyKYgMq/soA/v/hMCfnhr9NlzFpDHu3zwd6sfPPf7j+lWPPxMnaRvmySxE5xyAmJ6kG4w==

# Swagger
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# Default profile
spring.profiles.active=prod


# SSL / HTTPS
# The format used for the keystore. It could be set to JKS in case it is a JKS file
#server.ssl.key-store-type=PKCS12
## The path to the keystore containing the certificate
#server.ssl.key-store=classpath:pgl_backend.p12
## The password used to generate the certificate
#server.ssl.key-store-password=pgl_backend
#server.ssl.key-password=pgl_backend
## The alias mapped to the certificate
#server.ssl.key-alias=pgl_backend
#
#server.ssl.enabled=true